USE ISAdb
GO

DELETE FROM BackOrder
DELETE FROM PengirimanEkspedisiDetail
DELETE FROM PengirimanEkspedisi
DELETE FROM RekapKoliSubDetail
DELETE FROM RekapKoliDetail
DELETE FROM RekapKoli
DELETE FROM PenjualanPotonganDetail
DELETE FROM PenjualanPotongan
DELETE FROM SelisihDetail
DELETE FROM Selisih
DELETE FROM Koret
DELETE FROM KoreksiReturPenjualan
DELETE FROM KoreksiPenjualan
DELETE FROM ReturPenjualanDetail
DELETE FROM ReturPenjualanTarikanDetail
DELETE FROM ReturPenjualan
DELETE FROM NotaPenjualanDetail
DELETE FROM NotaPenjualan
DELETE FROM OrderPenjualanDetail
DELETE FROM OrderPenjualan
DELETE FROM KoreksiReturPembelian
DELETE FROM KoreksiPembelian
DELETE FROM ReturPembelianManualDetail
DELETE FROM ReturPembelianDetail
DELETE FROM ReturPembelian
DELETE FROM NotaPembelianDetail
DELETE FROM NotaPembelian
DELETE FROM OrderPembelianDetail
DELETE FROM OrderPembelian
DELETE FROM AccBonusSalesDetail
DELETE FROM AccBonusSales
DELETE FROM PeriodeGroup
DELETE FROM PengembalianDetail
DELETE FROM Pengembalian
DELETE FROM PeminjamanDetail
DELETE FROM Peminjaman
DELETE FROM AntarGudangDetail
DELETE FROM AntarGudang
DELETE FROM MutasiDetail
DELETE FROM Mutasi
DELETE FROM ClosingStok
DELETE FROM OpnameDetail3
DELETE FROM OpnameDetail2
DELETE FROM OpnameDetail1
DELETE FROM Opname
DELETE FROM OpnameHistory
DELETE FROM StandarStok
DELETE FROM StandarStokHistory
DELETE FROM StokGudang
DELETE FROM TargetSalesPerBarangDetail
DELETE FROM TargetSalesPerBarang
DELETE FROM TargetSales
DELETE FROM ReIDWil
DELETE FROM TPPC
DELETE FROM RPPC
DELETE FROM PT
DELETE FROM PostArea
DELETE FROM PostKota
DELETE FROM Perusahaan
DELETE FROM Pemasok
DELETE FROM Numerator
DELETE FROM KompensasiKerugian
DELETE FROM Kompensasi
DELETE FROM KoliTone
DELETE FROM KodePos
DELETE FROM KelompokBarang
DELETE FROM Kategori
DELETE FROM JPPC
DELETE FROM HPPC
DELETE FROM HistoryHPPA
DELETE FROM HistoryHPP
DELETE FROM HistoryBMK2
DELETE FROM HistoryBMK
DELETE FROM Gudang
DELETE FROM Expedisi
DELETE FROM DPJPPC
DELETE FROM DetailPlafon
DELETE FROM StokDetail
DELETE FROM StokGroup
DELETE FROM Collector
DELETE FROM Checker
DELETE FROM Cabang
DELETE FROM BarangBonusDetail
DELETE FROM BarangBonus
DELETE FROM StaffPenjualan
DELETE FROM Sopir
DELETE FROM PenanggungjawabRak
DELETE FROM TujuanExpedisi
DELETE FROM Stok
DELETE FROM TokoToSales
DELETE FROM Sales
DELETE FROM StatusToko
DELETE FROM Toko
