sqlcmd -S localhost\sqlexpress -E -t 0 -i AccountToko.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i BankKota.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i ClosingGL.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i KasirLog.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Numerator.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Saldo.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i TransaksiBank.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Perkiraan.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i PerkiraanKoneksi.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i PerkiraanKoneksiDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Bank.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Inden.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i kasbon.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i VoucherJournal.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i KartuPiutang.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i TransferMasuk.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i IndenDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i VoucherJournalDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i BBM.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Giro.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i TransferMasukDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i BBK.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i GiroInternal.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i BankDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Bukti.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i PinjamanPegawai.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i IndenSubDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i GiroTolak.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Tagihan.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i TagihanDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i IndenSuperDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i KartuPiutangDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i TagihanSubDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i GiroTolakDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i BuktiDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i DKN.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i DKNDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i ClosingGL.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Partner.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i PartnerDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i SubJournal.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i SubJournalDetail.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i DataCustomer.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i InOut.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i KartuPiutangLunas.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i SaldoTransferOtomatis.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i Saldo.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i SetoranFmApi.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i SetoranFmApiBayar.sql
sqlcmd -S localhost\sqlexpress -E -t 0 -i DataBank.sql

PAUSE