sqlcmd -S CRBISA -U sa -P password -t 0 -i ClosingStok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Mutasi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i MutasiDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i AntarGudang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i AntarGudangDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Peminjaman.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PeminjamanDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Pengembalian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PengembalianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PeriodeGroup.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OrderPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OrderPembelianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i NotaPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i NotaPembelianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPembelianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPembelianManualDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KoreksiPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KoreksiReturPembelian.sql
PAUSE