sqlcmd -S CRBISA -U sa -P password -t 0 -i Numerator.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Pemasok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Perusahaan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PostKota.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PostArea.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PT.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i RPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Tagih.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReIDWil.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TargetSales.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TargetSalesPerBarang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TargetSalesPerBarangDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StokGudang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StandarStokHistory.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StandarStok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameHistory.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Opname.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameDetail1.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameDetail2.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameDetail3.sql
PAUSE