usp_ACCDOPos_LIST
usp_ACCDOPos_LIST_FILTER_ROWID 
usp_ACCDOPOS_UPDATE 
usp_GetOVD
usp_GetNominalgiro
usp_RpJualkartuPiutang
usp_OrderPenjualan_GetHrgNet
usp_NotaPenjualan_CHEK
psp_PJ3_LinkToPiutang_ISA
psp_Potongan_LinkToPiutang_ISA
psp_PJT_LinkToPiutang_ISA
fnCekPiutangForBonus
usp_Piutang_CHEK
usp_RsOpac_UPLOAD_C1
usp_RsOpac_UPLOAD_ReturPenjualan_C1
usp_detailPlafon_Get
usp_detailPlafon_Refresh


usp_OrderPenjualanDetail_LIST_FILTER_HEADERID_2
[usp_CekStokRealTime]
[fnCekStokRealTime]	
[usp_NotaPenjualan_LIST_FILTER_DOID]
usp_OpnameHistory_INSERT
