USE ISAFinance_JKT
GO



INSERT INTO DBO.PJTtoBukti
SELECT * FROM ISAFinance.DBO.PJTtoBukti WHERE KPRecID NOT IN (SELECT KPRecID FROM DBO.PJTtoBukti)
AND BuktiRecID NOT IN (SELECT BuktiRecID FROM DBO.PJTtoBukti)
GO 