USE ISAdb 
GO
DELETE FROM ISAdb.dbo.Toko
GO
INSERT INTO ISAdb.dbo.Toko
(
	RowID, 
	TokoID, 
	NamaToko, 
	Alamat, 
	Kota, 
	Telp, 
	WilID, 
	PenanggungJawab, 
	KodeToko, 
	PiutangB, 
	PiutangJ, 
	Plafon, 
	ToJual, 
	ToRetPot, 
	JangkaWaktuKredit, 
	Cabang2, 
	Tgl1st, 
	Exist, 
	ClassID, 
	Catatan, 
	SyncFlag, 
	HariKirim, 
	KodePos, 
	Grade, 
	Plafon1st, 
	Flag, 
	Bentrok, 
	StatusAktif, 
	HariSales, 
	Daerah, 
	Propinsi, 
	AlamatRumah, 
	Pengelola, 
	TglLahir, 
	HP, 
	Status, 
	ThnBerdiri, 
	StatusRuko, 
	JmlCabang, 
	JmlSales, 
	Kinerja, 
	BidangUsaha, 
	RefSales, 
	RefCollector, 
	RefSupervisor, 
	PlafonSurvey, 
	LastUpdatedBy, 
	LastUpdatedTime
)
SELECT 
	NEWID(), 
	RTRIM(idtoko), 
	RTRIM(namatoko), 
	RTRIM(alamat), 
	RTRIM(kota), 
	RTRIM(notelp), 
	RTRIM(idwil), 
	RTRIM(pngjwb), 
	RTRIM(kd_toko), 
	piutang_b, 
	piutang_j, 
	plafon, 
	to_jual, 
	to_retpot, 
	jkw_kredit, 
	cab2, 
	tgl1st, 
	exist, 
	RTRIM(idclass), 
	RTRIM(catatan), 
	id_match, 
	hari_krm, 
	RTRIM(kd_pos), 
	RTRIM(grade), 
	plafon_1st, 
	RTRIM(flag), 
	bentrok, 
	lpasif, 
	hari_sls, 
	RTRIM(daerah), 
	propinsi, -- tidak di trim krn spacenya dibutuhkan utk ambil Stb(2 char from right) 
	RTRIM(alm_rumah), 
	RTRIM(pengelola), 
	tgl_lahir, 
	RTRIM(hp), 
	RTRIM(status), 
	RTRIM(th_berdiri), 
	lruko, 
	jml_cabang, 
	jml_sales, 
	RTRIM(kinerja), 
	RTRIM(bdg_usaha), 
	RTRIM(reff_sls), 
	RTRIM(reff_col), 
	RTRIM(reff_spv), 
	plf_survey, 
	'Admin', 
	GETDATE()
FROM OPENROWSET('VFPOLEDB', 'C:\SAS_Database\'; ' '; ' ', 'SELECT * FROM Toko')

GO

--DELETE FROM Toko WHERE TokoID = ''


--SELECT * FROM Toko 