//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ISA.Finance.DataTemplates {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsPembayaranHutang")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsPembayaranHutang : global::System.Data.DataSet {
        
        private dtTemplateDataTable tabledtTemplate;
        
        private dtMataUangDataTable tabledtMataUang;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsPembayaranHutang() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsPembayaranHutang(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtTemplate"] != null)) {
                    base.Tables.Add(new dtTemplateDataTable(ds.Tables["dtTemplate"]));
                }
                if ((ds.Tables["dtMataUang"] != null)) {
                    base.Tables.Add(new dtMataUangDataTable(ds.Tables["dtMataUang"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtTemplateDataTable dtTemplate {
            get {
                return this.tabledtTemplate;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtMataUangDataTable dtMataUang {
            get {
                return this.tabledtMataUang;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsPembayaranHutang cln = ((dsPembayaranHutang)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtTemplate"] != null)) {
                    base.Tables.Add(new dtTemplateDataTable(ds.Tables["dtTemplate"]));
                }
                if ((ds.Tables["dtMataUang"] != null)) {
                    base.Tables.Add(new dtMataUangDataTable(ds.Tables["dtMataUang"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabledtTemplate = ((dtTemplateDataTable)(base.Tables["dtTemplate"]));
            if ((initTable == true)) {
                if ((this.tabledtTemplate != null)) {
                    this.tabledtTemplate.InitVars();
                }
            }
            this.tabledtMataUang = ((dtMataUangDataTable)(base.Tables["dtMataUang"]));
            if ((initTable == true)) {
                if ((this.tabledtMataUang != null)) {
                    this.tabledtMataUang.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsPembayaranHutang";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsPembayaranHutang.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtTemplate = new dtTemplateDataTable();
            base.Tables.Add(this.tabledtTemplate);
            this.tabledtMataUang = new dtMataUangDataTable();
            base.Tables.Add(this.tabledtMataUang);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializedtTemplate() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializedtMataUang() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsPembayaranHutang ds = new dsPembayaranHutang();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void dtTemplateRowChangeEventHandler(object sender, dtTemplateRowChangeEvent e);
        
        public delegate void dtMataUangRowChangeEventHandler(object sender, dtMataUangRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtTemplateDataTable : global::System.Data.TypedTableBase<dtTemplateRow> {
            
            private global::System.Data.DataColumn columnPengeluaranUangRowID;
            
            private global::System.Data.DataColumn columnKoreksiBeliRowID;
            
            private global::System.Data.DataColumn columnMataUangRowID;
            
            private global::System.Data.DataColumn columnTanggal;
            
            private global::System.Data.DataColumn columnKeterangan;
            
            private global::System.Data.DataColumn columnPmbReferensi;
            
            private global::System.Data.DataColumn columnKurs;
            
            private global::System.Data.DataColumn columnPembIDR;
            
            private global::System.Data.DataColumn columnPembUSD;
            
            private global::System.Data.DataColumn columnPembORI;
            
            private global::System.Data.DataColumn columnSisaORI;
            
            private global::System.Data.DataColumn columnSisaUSD;
            
            private global::System.Data.DataColumn columnSisaIDR;
            
            private global::System.Data.DataColumn columnMataUangID;
            
            private global::System.Data.DataColumn columnHiRowID;
            
            private global::System.Data.DataColumn columnReturBeliRowID;
            
            private global::System.Data.DataColumn columnKoreksiReturBeliRowID;
            
            private global::System.Data.DataColumn columnPerusahaanDariRowID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtTemplateDataTable() {
                this.TableName = "dtTemplate";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtTemplateDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected dtTemplateDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PengeluaranUangRowIDColumn {
                get {
                    return this.columnPengeluaranUangRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KoreksiBeliRowIDColumn {
                get {
                    return this.columnKoreksiBeliRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MataUangRowIDColumn {
                get {
                    return this.columnMataUangRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TanggalColumn {
                get {
                    return this.columnTanggal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KeteranganColumn {
                get {
                    return this.columnKeterangan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PmbReferensiColumn {
                get {
                    return this.columnPmbReferensi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KursColumn {
                get {
                    return this.columnKurs;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PembIDRColumn {
                get {
                    return this.columnPembIDR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PembUSDColumn {
                get {
                    return this.columnPembUSD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PembORIColumn {
                get {
                    return this.columnPembORI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SisaORIColumn {
                get {
                    return this.columnSisaORI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SisaUSDColumn {
                get {
                    return this.columnSisaUSD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SisaIDRColumn {
                get {
                    return this.columnSisaIDR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MataUangIDColumn {
                get {
                    return this.columnMataUangID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HiRowIDColumn {
                get {
                    return this.columnHiRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ReturBeliRowIDColumn {
                get {
                    return this.columnReturBeliRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KoreksiReturBeliRowIDColumn {
                get {
                    return this.columnKoreksiReturBeliRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PerusahaanDariRowIDColumn {
                get {
                    return this.columnPerusahaanDariRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtTemplateRow this[int index] {
                get {
                    return ((dtTemplateRow)(this.Rows[index]));
                }
            }
            
            public event dtTemplateRowChangeEventHandler dtTemplateRowChanging;
            
            public event dtTemplateRowChangeEventHandler dtTemplateRowChanged;
            
            public event dtTemplateRowChangeEventHandler dtTemplateRowDeleting;
            
            public event dtTemplateRowChangeEventHandler dtTemplateRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdddtTemplateRow(dtTemplateRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtTemplateRow AdddtTemplateRow(
                        System.Guid PengeluaranUangRowID, 
                        System.Guid KoreksiBeliRowID, 
                        System.Guid MataUangRowID, 
                        System.DateTime Tanggal, 
                        string Keterangan, 
                        string PmbReferensi, 
                        double Kurs, 
                        double PembIDR, 
                        double PembUSD, 
                        double PembORI, 
                        double SisaORI, 
                        double SisaUSD, 
                        double SisaIDR, 
                        string MataUangID, 
                        System.Guid HiRowID, 
                        System.Guid ReturBeliRowID, 
                        System.Guid KoreksiReturBeliRowID, 
                        string PerusahaanDariRowID) {
                dtTemplateRow rowdtTemplateRow = ((dtTemplateRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        PengeluaranUangRowID,
                        KoreksiBeliRowID,
                        MataUangRowID,
                        Tanggal,
                        Keterangan,
                        PmbReferensi,
                        Kurs,
                        PembIDR,
                        PembUSD,
                        PembORI,
                        SisaORI,
                        SisaUSD,
                        SisaIDR,
                        MataUangID,
                        HiRowID,
                        ReturBeliRowID,
                        KoreksiReturBeliRowID,
                        PerusahaanDariRowID};
                rowdtTemplateRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtTemplateRow);
                return rowdtTemplateRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                dtTemplateDataTable cln = ((dtTemplateDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtTemplateDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnPengeluaranUangRowID = base.Columns["PengeluaranUangRowID"];
                this.columnKoreksiBeliRowID = base.Columns["KoreksiBeliRowID"];
                this.columnMataUangRowID = base.Columns["MataUangRowID"];
                this.columnTanggal = base.Columns["Tanggal"];
                this.columnKeterangan = base.Columns["Keterangan"];
                this.columnPmbReferensi = base.Columns["PmbReferensi"];
                this.columnKurs = base.Columns["Kurs"];
                this.columnPembIDR = base.Columns["PembIDR"];
                this.columnPembUSD = base.Columns["PembUSD"];
                this.columnPembORI = base.Columns["PembORI"];
                this.columnSisaORI = base.Columns["SisaORI"];
                this.columnSisaUSD = base.Columns["SisaUSD"];
                this.columnSisaIDR = base.Columns["SisaIDR"];
                this.columnMataUangID = base.Columns["MataUangID"];
                this.columnHiRowID = base.Columns["HiRowID"];
                this.columnReturBeliRowID = base.Columns["ReturBeliRowID"];
                this.columnKoreksiReturBeliRowID = base.Columns["KoreksiReturBeliRowID"];
                this.columnPerusahaanDariRowID = base.Columns["PerusahaanDariRowID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnPengeluaranUangRowID = new global::System.Data.DataColumn("PengeluaranUangRowID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPengeluaranUangRowID);
                this.columnKoreksiBeliRowID = new global::System.Data.DataColumn("KoreksiBeliRowID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKoreksiBeliRowID);
                this.columnMataUangRowID = new global::System.Data.DataColumn("MataUangRowID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMataUangRowID);
                this.columnTanggal = new global::System.Data.DataColumn("Tanggal", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTanggal);
                this.columnKeterangan = new global::System.Data.DataColumn("Keterangan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKeterangan);
                this.columnPmbReferensi = new global::System.Data.DataColumn("PmbReferensi", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPmbReferensi);
                this.columnKurs = new global::System.Data.DataColumn("Kurs", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKurs);
                this.columnPembIDR = new global::System.Data.DataColumn("PembIDR", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPembIDR);
                this.columnPembUSD = new global::System.Data.DataColumn("PembUSD", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPembUSD);
                this.columnPembORI = new global::System.Data.DataColumn("PembORI", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPembORI);
                this.columnSisaORI = new global::System.Data.DataColumn("SisaORI", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSisaORI);
                this.columnSisaUSD = new global::System.Data.DataColumn("SisaUSD", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSisaUSD);
                this.columnSisaIDR = new global::System.Data.DataColumn("SisaIDR", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSisaIDR);
                this.columnMataUangID = new global::System.Data.DataColumn("MataUangID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMataUangID);
                this.columnHiRowID = new global::System.Data.DataColumn("HiRowID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHiRowID);
                this.columnReturBeliRowID = new global::System.Data.DataColumn("ReturBeliRowID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReturBeliRowID);
                this.columnKoreksiReturBeliRowID = new global::System.Data.DataColumn("KoreksiReturBeliRowID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKoreksiReturBeliRowID);
                this.columnPerusahaanDariRowID = new global::System.Data.DataColumn("PerusahaanDariRowID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPerusahaanDariRowID);
                this.columnKurs.DefaultValue = ((double)(0));
                this.columnPembIDR.DefaultValue = ((double)(0));
                this.columnPembUSD.DefaultValue = ((double)(0));
                this.columnPembORI.DefaultValue = ((double)(0));
                this.columnSisaORI.DefaultValue = ((double)(0));
                this.columnSisaUSD.DefaultValue = ((double)(0));
                this.columnSisaIDR.DefaultValue = ((double)(0));
                this.columnMataUangID.DefaultValue = ((string)(""));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtTemplateRow NewdtTemplateRow() {
                return ((dtTemplateRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtTemplateRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(dtTemplateRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtTemplateRowChanged != null)) {
                    this.dtTemplateRowChanged(this, new dtTemplateRowChangeEvent(((dtTemplateRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtTemplateRowChanging != null)) {
                    this.dtTemplateRowChanging(this, new dtTemplateRowChangeEvent(((dtTemplateRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtTemplateRowDeleted != null)) {
                    this.dtTemplateRowDeleted(this, new dtTemplateRowChangeEvent(((dtTemplateRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtTemplateRowDeleting != null)) {
                    this.dtTemplateRowDeleting(this, new dtTemplateRowChangeEvent(((dtTemplateRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovedtTemplateRow(dtTemplateRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsPembayaranHutang ds = new dsPembayaranHutang();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtTemplateDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtMataUangDataTable : global::System.Data.TypedTableBase<dtMataUangRow> {
            
            private global::System.Data.DataColumn columnMataUangRowID;
            
            private global::System.Data.DataColumn columnMataUangID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtMataUangDataTable() {
                this.TableName = "dtMataUang";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtMataUangDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected dtMataUangDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MataUangRowIDColumn {
                get {
                    return this.columnMataUangRowID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MataUangIDColumn {
                get {
                    return this.columnMataUangID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtMataUangRow this[int index] {
                get {
                    return ((dtMataUangRow)(this.Rows[index]));
                }
            }
            
            public event dtMataUangRowChangeEventHandler dtMataUangRowChanging;
            
            public event dtMataUangRowChangeEventHandler dtMataUangRowChanged;
            
            public event dtMataUangRowChangeEventHandler dtMataUangRowDeleting;
            
            public event dtMataUangRowChangeEventHandler dtMataUangRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdddtMataUangRow(dtMataUangRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtMataUangRow AdddtMataUangRow(System.Guid MataUangRowID, string MataUangID) {
                dtMataUangRow rowdtMataUangRow = ((dtMataUangRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        MataUangRowID,
                        MataUangID};
                rowdtMataUangRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtMataUangRow);
                return rowdtMataUangRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                dtMataUangDataTable cln = ((dtMataUangDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtMataUangDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnMataUangRowID = base.Columns["MataUangRowID"];
                this.columnMataUangID = base.Columns["MataUangID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnMataUangRowID = new global::System.Data.DataColumn("MataUangRowID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMataUangRowID);
                this.columnMataUangID = new global::System.Data.DataColumn("MataUangID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMataUangID);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtMataUangRow NewdtMataUangRow() {
                return ((dtMataUangRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtMataUangRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(dtMataUangRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtMataUangRowChanged != null)) {
                    this.dtMataUangRowChanged(this, new dtMataUangRowChangeEvent(((dtMataUangRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtMataUangRowChanging != null)) {
                    this.dtMataUangRowChanging(this, new dtMataUangRowChangeEvent(((dtMataUangRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtMataUangRowDeleted != null)) {
                    this.dtMataUangRowDeleted(this, new dtMataUangRowChangeEvent(((dtMataUangRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtMataUangRowDeleting != null)) {
                    this.dtMataUangRowDeleting(this, new dtMataUangRowChangeEvent(((dtMataUangRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovedtMataUangRow(dtMataUangRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsPembayaranHutang ds = new dsPembayaranHutang();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtMataUangDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class dtTemplateRow : global::System.Data.DataRow {
            
            private dtTemplateDataTable tabledtTemplate;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtTemplateRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtTemplate = ((dtTemplateDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid PengeluaranUangRowID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtTemplate.PengeluaranUangRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PengeluaranUangRowID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.PengeluaranUangRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid KoreksiBeliRowID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtTemplate.KoreksiBeliRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KoreksiBeliRowID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.KoreksiBeliRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid MataUangRowID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtTemplate.MataUangRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MataUangRowID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.MataUangRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime Tanggal {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtTemplate.TanggalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Tanggal\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.TanggalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Keterangan {
                get {
                    try {
                        return ((string)(this[this.tabledtTemplate.KeteranganColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Keterangan\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.KeteranganColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PmbReferensi {
                get {
                    try {
                        return ((string)(this[this.tabledtTemplate.PmbReferensiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PmbReferensi\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.PmbReferensiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double Kurs {
                get {
                    if (this.IsKursNull()) {
                        return 0;
                    }
                    else {
                        return ((double)(this[this.tabledtTemplate.KursColumn]));
                    }
                }
                set {
                    this[this.tabledtTemplate.KursColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double PembIDR {
                get {
                    if (this.IsPembIDRNull()) {
                        return 0;
                    }
                    else {
                        return ((double)(this[this.tabledtTemplate.PembIDRColumn]));
                    }
                }
                set {
                    this[this.tabledtTemplate.PembIDRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double PembUSD {
                get {
                    if (this.IsPembUSDNull()) {
                        return 0;
                    }
                    else {
                        return ((double)(this[this.tabledtTemplate.PembUSDColumn]));
                    }
                }
                set {
                    this[this.tabledtTemplate.PembUSDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double PembORI {
                get {
                    if (this.IsPembORINull()) {
                        return 0;
                    }
                    else {
                        return ((double)(this[this.tabledtTemplate.PembORIColumn]));
                    }
                }
                set {
                    this[this.tabledtTemplate.PembORIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double SisaORI {
                get {
                    if (this.IsSisaORINull()) {
                        return 0;
                    }
                    else {
                        return ((double)(this[this.tabledtTemplate.SisaORIColumn]));
                    }
                }
                set {
                    this[this.tabledtTemplate.SisaORIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double SisaUSD {
                get {
                    if (this.IsSisaUSDNull()) {
                        return 0;
                    }
                    else {
                        return ((double)(this[this.tabledtTemplate.SisaUSDColumn]));
                    }
                }
                set {
                    this[this.tabledtTemplate.SisaUSDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double SisaIDR {
                get {
                    if (this.IsSisaIDRNull()) {
                        return 0;
                    }
                    else {
                        return ((double)(this[this.tabledtTemplate.SisaIDRColumn]));
                    }
                }
                set {
                    this[this.tabledtTemplate.SisaIDRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MataUangID {
                get {
                    try {
                        return ((string)(this[this.tabledtTemplate.MataUangIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MataUangID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.MataUangIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid HiRowID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtTemplate.HiRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'HiRowID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.HiRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid ReturBeliRowID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtTemplate.ReturBeliRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ReturBeliRowID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.ReturBeliRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid KoreksiReturBeliRowID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtTemplate.KoreksiReturBeliRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KoreksiReturBeliRowID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.KoreksiReturBeliRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PerusahaanDariRowID {
                get {
                    try {
                        return ((string)(this[this.tabledtTemplate.PerusahaanDariRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PerusahaanDariRowID\' in table \'dtTemplate\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtTemplate.PerusahaanDariRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPengeluaranUangRowIDNull() {
                return this.IsNull(this.tabledtTemplate.PengeluaranUangRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPengeluaranUangRowIDNull() {
                this[this.tabledtTemplate.PengeluaranUangRowIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKoreksiBeliRowIDNull() {
                return this.IsNull(this.tabledtTemplate.KoreksiBeliRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKoreksiBeliRowIDNull() {
                this[this.tabledtTemplate.KoreksiBeliRowIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMataUangRowIDNull() {
                return this.IsNull(this.tabledtTemplate.MataUangRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMataUangRowIDNull() {
                this[this.tabledtTemplate.MataUangRowIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTanggalNull() {
                return this.IsNull(this.tabledtTemplate.TanggalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTanggalNull() {
                this[this.tabledtTemplate.TanggalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKeteranganNull() {
                return this.IsNull(this.tabledtTemplate.KeteranganColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKeteranganNull() {
                this[this.tabledtTemplate.KeteranganColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPmbReferensiNull() {
                return this.IsNull(this.tabledtTemplate.PmbReferensiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPmbReferensiNull() {
                this[this.tabledtTemplate.PmbReferensiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKursNull() {
                return this.IsNull(this.tabledtTemplate.KursColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKursNull() {
                this[this.tabledtTemplate.KursColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPembIDRNull() {
                return this.IsNull(this.tabledtTemplate.PembIDRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPembIDRNull() {
                this[this.tabledtTemplate.PembIDRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPembUSDNull() {
                return this.IsNull(this.tabledtTemplate.PembUSDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPembUSDNull() {
                this[this.tabledtTemplate.PembUSDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPembORINull() {
                return this.IsNull(this.tabledtTemplate.PembORIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPembORINull() {
                this[this.tabledtTemplate.PembORIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSisaORINull() {
                return this.IsNull(this.tabledtTemplate.SisaORIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSisaORINull() {
                this[this.tabledtTemplate.SisaORIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSisaUSDNull() {
                return this.IsNull(this.tabledtTemplate.SisaUSDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSisaUSDNull() {
                this[this.tabledtTemplate.SisaUSDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSisaIDRNull() {
                return this.IsNull(this.tabledtTemplate.SisaIDRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSisaIDRNull() {
                this[this.tabledtTemplate.SisaIDRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMataUangIDNull() {
                return this.IsNull(this.tabledtTemplate.MataUangIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMataUangIDNull() {
                this[this.tabledtTemplate.MataUangIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHiRowIDNull() {
                return this.IsNull(this.tabledtTemplate.HiRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHiRowIDNull() {
                this[this.tabledtTemplate.HiRowIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsReturBeliRowIDNull() {
                return this.IsNull(this.tabledtTemplate.ReturBeliRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetReturBeliRowIDNull() {
                this[this.tabledtTemplate.ReturBeliRowIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKoreksiReturBeliRowIDNull() {
                return this.IsNull(this.tabledtTemplate.KoreksiReturBeliRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKoreksiReturBeliRowIDNull() {
                this[this.tabledtTemplate.KoreksiReturBeliRowIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPerusahaanDariRowIDNull() {
                return this.IsNull(this.tabledtTemplate.PerusahaanDariRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPerusahaanDariRowIDNull() {
                this[this.tabledtTemplate.PerusahaanDariRowIDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class dtMataUangRow : global::System.Data.DataRow {
            
            private dtMataUangDataTable tabledtMataUang;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtMataUangRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtMataUang = ((dtMataUangDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid MataUangRowID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtMataUang.MataUangRowIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MataUangRowID\' in table \'dtMataUang\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtMataUang.MataUangRowIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MataUangID {
                get {
                    try {
                        return ((string)(this[this.tabledtMataUang.MataUangIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MataUangID\' in table \'dtMataUang\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtMataUang.MataUangIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMataUangRowIDNull() {
                return this.IsNull(this.tabledtMataUang.MataUangRowIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMataUangRowIDNull() {
                this[this.tabledtMataUang.MataUangRowIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMataUangIDNull() {
                return this.IsNull(this.tabledtMataUang.MataUangIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMataUangIDNull() {
                this[this.tabledtMataUang.MataUangIDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class dtTemplateRowChangeEvent : global::System.EventArgs {
            
            private dtTemplateRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtTemplateRowChangeEvent(dtTemplateRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtTemplateRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class dtMataUangRowChangeEvent : global::System.EventArgs {
            
            private dtMataUangRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtMataUangRowChangeEvent(dtMataUangRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtMataUangRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591