sqlcmd -S CRBISA -U sa -P password -t 0 -i BackOrder.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PengirimanEkspedisiDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PengirimanEkspedisi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i RekapKoliSubDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i RekapKoliDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i RekapKoli.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PenjualanPotonganDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PenjualanPotongan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i SelisihDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Selisih.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Koret.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i BackOrder.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KoreksiReturPenjualan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KoreksiPenjualan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ACCBonusSalesDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ACCBonusSales.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPenjualanDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPenjualan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i NotaPenjualanDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i NotaPenjualan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Kompensasi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OrderPenjualanDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OrderPenjualan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KoreksiReturPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KoreksiPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPembelianManualDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPembelianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReturPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i NotaPembelianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i NotaPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OrderPembelianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OrderPembelian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PeriodeGroup.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PengembalianDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Pengembalian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PeminjamanDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Peminjaman.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i AntarGudangDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i AntarGudang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i MutasiDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Mutasi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ClosingStok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameDetail3.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameDetail2.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameDetail1.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Opname.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i OpnameHistory.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StandarStok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StandarStokHistory.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StokGudang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TargetSalesPerBarangDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TargetSalesPerBarang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TargetSales.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i ReIDWil.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Tagih.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i RPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PT.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PostArea.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PostKota.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Perusahaan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Pemasok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Numerator.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KompensasiKerugian.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KoliTone.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KodePos.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KelompokBarang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Kategori.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i JPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i HPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i HistoryHPPA.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i HistoryHPP.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i HistoryBMK2.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i HistoryBMK.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Gudang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Giro.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Expedisi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i DPJPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i DetailPlafon.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StokDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PeriodeGroup.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StokGroup.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Collector.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Checker.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Cabang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i BarangBonusDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i BarangBonus.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StafPenjualan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Sopir.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PenanggungjawabRak.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TujuanExpedisi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Stok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TokoToSales.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Sales.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StatusToko.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Toko.sql
PAUSE