sqlcmd -S CRBISA -U sa -P password -t 0 -i KoliTone.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KodePos.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i KelompokBarang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Kategori.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i JPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i HPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Gudang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Expedisi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i DPJPPC.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i DetailPlafon.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StokDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PeriodeGroup.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StokGroup.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Collector.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Checker.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Cabang.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i BarangBonusDetail.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i BarangBonus.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StafPenjualan.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Sopir.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i PenanggungjawabRak.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TujuanExpedisi.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Stok.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i TokoToSales.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Sales.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i StatusToko.sql
sqlcmd -S CRBISA -U sa -P password -t 0 -i Toko.sql
PAUSE