--2005
USE ISAdb
GO
DBCC SHRINKFILE(ISAdb_log, 1)
BACKUP LOG ISAdb WITH TRUNCATE_ONLY
DBCC SHRINKFILE(ISAdb_log, 1)  

--2008

ALTER DATABASE [TestDb] SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKFILE(TestDbLog, 1000)
ALTER DATABASE [TestDb] SET RECOVERY FULL WITH NO_WAIT